Cleaned up the README
kitelightning/LivePP pull request #3
Opened 2018-08-11 18:26 UTC by rlabrecque

Reworded a bunch of sections, fixed some typos, added some additional information that's required since it was last modified, and generally cleaned it up.

2018-10-08 08:23 UTC, Kapsler requested changes

2018-10-08 08:23 UTC, Kapsler commented on README.md
> -	 **NOTE:** UBT support for UniqueBuildEnvironment doesn't work  if you're game is not in a subdirectory of the UnrealEngine. Your best bet is to modify the buildconfiguration.xml(https://docs.unreal
Could you also clarify on this part a little? What exactly does "Subdirectory of UnrealEngine" mean? You could add "(e.g. UE_4.XX/Engine/Games/YourGame/") or similar.

Also i think that this section is not correct. The current code in version 4.20.3 does not have the tags " [XmlConfigFile(Category = "BuildConfiguration")]" which means you can't set the arguments in the "BuildConfiguration.xml".

Can you also change "if you're game is not" to " if your game is not", while you are at it?

2018-12-21 05:01 UTC, ikrima commented on README.md
> -	 **NOTE:** UBT support for UniqueBuildEnvironment doesn't work  if you're game is not in a subdirectory of the UnrealEngine. Your best bet is to modify the buildconfiguration.xml(https://docs.unreal
👍

2018-12-21 05:02 UTC, ikrima approved these changes

2018-12-21 05:04 UTC, merged